### ISSUE TITLE
关于kdcl的版本

### ISSUE THREAD

**Issue by zichihuanian** [shaoeric/Online-Knowledge-Distillation-via-Collaborative-Learning#1]
你好，感谢你的代码分享，在kdcl论文中有四种版本的kdcl，分别是naive，linear、minlogit和general，请问你这个是哪一种？

**Comment by shaoeric** [comment]
> 你好，感谢你的代码分享，在kdcl论文中有四种版本的kdcl，分别是naive，linear、minlogit和general，请问你这个是哪一种？

您好，我没有严格的按照这四个方法去做，我只是单纯的把多个模型输出集成作为softlabel。把这个改写成naive版本改不了多少代码。欢迎讨论(^-^)

**Comment by maggieHao** [comment]
你好，如果想考虑实现linear的话，您有思路应该怎么实现凸优化问题的求解吗？

**Comment by shaoeric** [comment]
@maggieHao 
这里alpha只是个线性系数，每个子网络都平均分配我认为就可以，论文中并没有给如何设置这个系数。至于如何优化，我觉得论文并没有说清楚两个模型的输出z与y分别计算完交叉熵损失后，应该怎么结合，是平均后反向传播 还是像naive一样取最小的再传播，这我就不太清楚了。
