### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by giantke** [shaoeric/Online-Knowledge-Distillation-via-Collaborative-Learning#2]
感谢分享！有个小问题，在train.py中line 71，有了torch数组outputs为什么还要重新做一个列表out_list，后面做kl loss的时候直接用outputs[model_idx]不行吗，或者是有什么特殊用意，请指教

**Comment by shaoeric** [comment]
@giantke 是这样的，用list保存的tensor是有梯度的，outputs数组最后做平均是要保留没有梯度的。如果不使用list，会报错，计算图被free之类的错误
